sudo: required
services: 
  - docker

# build test images
before_install:
  - docker build -t pranavj1001/smcda-client-test -f ./client/dev.Dockerfile ./client

# run tests
script:
  - docker run -e CI=true pranavj1001/smcda-client-test npm test

after_success:
  # build production images
  - docker build -t pranavj1001/smcda-client ./client
  - docker build -t pranavj1001/smcda-server ./server
  - docker build -t pranavj1001/smcda-worker ./worker
  - docker build -t pranavj1001/smcda-nginx ./nginx
  # Log in to DOCKER CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push production images to docker hub
  - docker push pranavj1001/smcda-client
  - docker push pranavj1001/smcda-server
  - docker push pranavj1001/smcda-worker
  - docker push pranavj1001/smcda-nginx

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: sample-multi-container-docker-app
  env: SampleMultiContainerDockerApp-env
  bucket_name: elasticbeanstalk-ap-south-1-087431259218
  bucket_path: smcda
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY